### ISSUE TITLE
Создать REST ресурс

### ISSUE THREAD

**Issue by asaushkin** [chelnyedu/dropwizard-rest#11]
Создать REST ресурс - Глава 4

**Comment by Nataly-Sagel** [comment]
окей

**Comment by asikabi** [comment]
Для выполнения задачи была создана ветка RESTres

**Comment by ilya746** [comment]
Для выполнения задачи была создана ветка RESTResources

**Comment by Nataly-Sagel** [comment]
Была создана ветка RestResSagel

**Comment by asikabi** [comment]
Ресурс создан
