### ISSUE TITLE
Using Database

### ISSUE THREAD

**Issue by asaushkin** [chelnyedu/dropwizard-rest#21]
Глава 6. Для юнит-тестировния использовать мок объекты. Для примера использования мок объектов смотреть сюда: https://examples.javacodegeeks.com/core-java/mockito/mockito-mock-database-connection-example/

**Comment by asaushkin** [comment]
Выполнять после главы 5 соответственно.

**Comment by ilya746** [comment]
для выполнения заданий из главы 6 была создана ветка DBDropwizard

**Comment by asaushkin** [comment]
Соединение с БД выполнить по примеру: https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-java

**Comment by Nataly-Sagel** [comment]
для выполнения заданий из главы 6 была создана ветка DatabaseSagel

**Comment by asaushkin** [comment]
И необходимо продумать, как будут созданы таблицы, возможно при запуске приложения, стоит проверять, существуют ли нужные таблицы и если нет, то создавать их.

**Comment by asaushkin** [comment]
В dropwizard есть встроенный механизм наката миграций, будет неплохо, если вы с ним разберётесь http://www.dropwizard.io/0.7.1/docs/manual/migrations.html

**Comment by asikabi** [comment]
для выполнения заданий из главы 6 была создана ветка DBconnection
