### ISSUE TITLE
Разобраться с миграциями

### ISSUE THREAD

**Issue by asaushkin** [chelnyedu/dropwizard-rest#26]
Разобраться с миграциями, подготовить миграцию для создания таблиц(ы) которая используется в книге.

http://www.dropwizard.io/0.7.1/docs/manual/migrations.html

Пример можно посмотреть и здесь: https://github.com/alexroussos/dropwizard-heroku-example

**Comment by asaushkin** [comment]
Про liquibase тоже немножко нужно будет почитать: http://www.liquibase.org/quickstart.html

**Comment by asikabi** [comment]
Для создания миграция была создана ветка DWMigration.

**Comment by ilya746** [comment]
Для создания миграций была создана ветка Migrations

**Comment by Nataly-Sagel** [comment]
branch MigrationSagel
