### ISSUE TITLE
Restfull service

### ISSUE THREAD

**Issue by ilya746** [chelnyedu/dropwizard-rest#44]
Исследовать новый restFullService
Разработать новый  rest клиент

**Comment by Nataly-Sagel** [comment]
Это как я понимаю надо делать уже в новом проекте?

**Comment by asaushkin** [comment]
> Разработать новый rest клиент

в новом

> Исследовать новый restFullService

вот это непонятно, что такое. наверное исследовать клиентские библиотеки для доступа к REST? если да, то тоже в новом.

**Comment by Nataly-Sagel** [comment]
хорошо
